language: ruby
rvm:
  - 2.6.0
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow-dupe --request-delay 1 --white-list stackoverflow.com,igor.io,toranproxy.com,laravel-china.org,drupal.org,phpindonesia.id,packagist.in
notifications:
  email: false
